- name: Remove existing dotfiles repository
  become: true
  file:
    path: "{{ home_dir }}/repos/dotfiles"
    state: absent

- name: Clone the dotfiles repository
  git:
    repo: "https://github.com/mxvoloshin/dotfiles"
    dest: "{{ home_dir }}/repos/dotfiles"
    update: yes
    clone: yes
