- name: Configure Git user.name
  command: git config --global user.name "Maksym Voloshyn"

- name: Configure Git user.email
  command: git config --global user.email "mx.voloshin@gmail.com"

- name: Check .gitconfig file contents
  command: cat /home/{{ ansible_user }}/.gitconfig
  register: gitconfig_contents

- name: Show .gitconfig contents
  debug:
    var: gitconfig_contents.stdout
