- name: Install tmux
  become: true
  apt:
    name:
      - tmux
    state: present
    update_cache: yes

- name: Create the directory for tmux plugins
  file:
    path: "{{ home_dir }}/.config/tmux/plugins/catppuccin"
    state: directory
    mode: "0755"

- name: Clone the Catppuccin tmux theme repository
  git:
    repo: https://github.com/catppuccin/tmux.git
    dest: "{{ home_dir }}/.config/tmux/plugins/catppuccin/tmux"
    version: v2.1.2

- name: Clone TPM repo
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
    clone: yes
    update: yes

- name: Replace .tmux.conf with the one from the dotfiles repository
  copy:
    src: "{{ home_dir }}/repos/dotfiles/.tmux.conf"
    dest: "{{ home_dir }}/.tmux.conf"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
    force: yes
    remote_src: yes # Indicates that the source file is on the remote machine
