- name: Remove existing zsh-autosuggestions directory
  become: true
  file:
    path: "{{ home_dir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    state: absent

- name: Clone zsh-autosuggestions plugin
  git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "{{ home_dir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    update: yes
    clone: yes

- name: Remove existing zsh-syntax-highlighting directory
  become: true
  file:
    path: "{{ home_dir }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    state: absent

- name: Clone zsh-syntax-highlighting plugin
  git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "{{ home_dir }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    update: yes
    clone: yes

- name: Remove existing zsh-completions directory
  become: true
  file:
    path: "{{ home_dir }}/.oh-my-zsh/custom/plugins/zsh-completions"
    state: absent

- name: Clone zsh-completions plugin
  git:
    repo: "https://github.com/zsh-users/zsh-completions.git"
    dest: "{{ home_dir }}/.oh-my-zsh/custom/plugins/zsh-completions"
    update: yes
    clone: yes

- name: Remove existing zsh-history-substring-search directory
  become: true
  file:
    path: "{{ home_dir }}/.oh-my-zsh/custom/plugins/zsh-history-substring-search"
    state: absent

- name: Clone zsh-history-substring-search plugin
  git:
    repo: "https://github.com/zsh-users/zsh-history-substring-search.git"
    dest: "{{ home_dir }}/.oh-my-zsh/custom/plugins/zsh-history-substring-search"
    update: yes
    clone: yes

- name: Replace .zshrc with the one from the dotfiles repository
  copy:
    src: "/home/{{ ansible_user }}/repos/dotfiles/.zshrc"
    dest: "/home/{{ ansible_user }}/.zshrc"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
    force: yes
    remote_src: yes # Indicates that the source file is on the remote machine
