- name: Install .NET SDK 8.0
  become: true
  apt:
    name: "dotnet-sdk-8.0"
    state: present

- name: Install csharpier globally
  ansible.builtin.shell:
    cmd: dotnet tool install -g csharpier
  environment:
    PATH: "{{ ansible_env.HOME }}/.dotnet/tools:{{ ansible_env.PATH }}"
  register: csharpier_install
  failed_when: false

- name: Debug csharpier install output
  ansible.builtin.debug:
    var: csharpier_install
