- name: Install Python 3 if not already present
  raw: |
    if ! command -v python3 > /dev/null 2>&1; then
      apt-get update && apt-get install -y python3;
    fi
  changed_when: false # Assume the state doesn't change if Python 3 is already installed

- name: Ensure pip is installed
  raw: |
    if ! command -v pip3 > /dev/null 2>&1; then
      apt-get install -y python3-pip;
    fi
  changed_when: false # Assume the state doesn't change if Python 3 is already installed

- name: Install python3-venv if not installed
  apt:
    name: python3-venv

- name: Create a virtual environment
  command: python3 -m venv /home/{{ ansible_user }}/myenv
  become: true

- name: Install six and ansible in the virtual environment
  command: /home/{{ ansible_user }}/myenv/bin/pip install six ansible
