# PowerShell Terminal Setup Script
# Run this script as Administrator for best results

Write-Host "=== PowerShell Terminal Setup ===" -ForegroundColor Cyan
Write-Host ""

# Check if running as Administrator
$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    Write-Host "Warning: Not running as Administrator. Some installations might fail." -ForegroundColor Yellow
    Write-Host "Consider running: Start-Process powershell -Verb RunAs" -ForegroundColor Yellow
    Write-Host ""
}

# Set execution policy if needed
Write-Host "Setting execution policy..." -ForegroundColor Green
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser -Force

# Install PowerShell modules
Write-Host "Installing PowerShell modules..." -ForegroundColor Green
$modules = @(
    "PSReadLine",
    "Terminal-Icons",
    "PSFzf",
    "z",
    "posh-git"
)

foreach ($module in $modules) {
    Write-Host "  Installing $module..." -ForegroundColor Yellow
    Install-Module -Name $module -Repository PSGallery -Scope CurrentUser -Force -SkipPublisherCheck
}

# Install command-line tools using winget
Write-Host ""
Write-Host "Installing command-line tools..." -ForegroundColor Green

$tools = @(
    @{Name="fzf"; Id="junegunn.fzf"},
    @{Name="fd"; Id="sharkdp.fd"},
    @{Name="ripgrep"; Id="BurntSushi.ripgrep.MSVC"},
    @{Name="bat"; Id="sharkdp.bat"},
    @{Name="zoxide"; Id="ajeetdsouza.zoxide"},
    @{Name="neovim"; Id="Neovim.Neovim"},
    @{Name="btop"; Id="aristocratos.btop"},
    @{Name="delta"; Id="dandavison.delta"},
    @{Name="Everything"; Id="voidtools.Everything"},
    @{Name="eza"; Id="eza-community.eza"}
)

foreach ($tool in $tools) {
    Write-Host "  Installing $($tool.Name)..." -ForegroundColor Yellow
    try {
        winget install --id $tool.Id --source winget --silent --accept-package-agreements --accept-source-agreements
    } catch {
        Write-Host "    Failed to install $($tool.Name). You may need to install it manually." -ForegroundColor Red
    }
}

# Configure git to use delta
Write-Host ""
Write-Host "Configuring git to use delta for diffs..." -ForegroundColor Green
git config --global core.pager delta
git config --global interactive.diffFilter "delta --color-only"
git config --global delta.navigate true
git config --global delta.side-by-side true
git config --global merge.conflictstyle diff3
git config --global diff.colorMoved default

# Create PowerShell profile
Write-Host ""
Write-Host "Creating PowerShell profile..." -ForegroundColor Green

$profileContent = @'
# PowerShell Profile Configuration
# Auto-generated by setup script

# Oh My Posh - Initialize your prompt theme
# Replace 'paradox' with your preferred theme name
oh-my-posh init pwsh --config "$env:POSH_THEMES_PATH\catppuccin_frappe.omp.json" | Invoke-Expression

# PSReadLine - Enhanced command line editing
Import-Module PSReadLine
Set-PSReadLineOption -PredictionSource History
Set-PSReadLineOption -PredictionViewStyle ListView
Set-PSReadLineOption -EditMode Windows
Set-PSReadLineOption -HistorySearchCursorMovesToEnd
Set-PSReadLineKeyHandler -Key UpArrow -Function HistorySearchBackward
Set-PSReadLineKeyHandler -Key DownArrow -Function HistorySearchForward
Set-PSReadLineKeyHandler -Key Tab -Function MenuComplete

# Terminal-Icons - Add icons to file listings
Import-Module Terminal-Icons

# PSFzf - Fuzzy finder for files and command history
Import-Module PSFzf
Set-PsFzfOption -PSReadlineChordProvider 'Ctrl+t'
Set-PsFzfOption -PSReadlineChordReverseHistory 'Ctrl+r'

# Zoxide - Smarter directory jumper (replaces z)
Invoke-Expression (& { (zoxide init powershell | Out-String) })

# posh-git - Git integration and enhanced tab completion
Import-Module posh-git

# Aliases
Set-Alias -Name ll -Value Get-ChildItem
Set-Alias -Name ls -Value eza
Set-Alias -Name cat -Value bat

# Custom functions
function Update-Profile {
    & $PROFILE
}

function Get-PublicIP {
    (Invoke-WebRequest -Uri "https://api.ipify.org").Content
}

# eza aliases for common operations
function l { eza -l --icons }
function la { eza -la --icons }
function lt { eza -l --tree --level=2 --icons }

# Welcome message
Write-Host "PowerShell loaded with enhancements!" -ForegroundColor Green
Write-Host "Ctrl+T: Fuzzy find | Ctrl+R: History search | z/zi: Jump to dirs" -ForegroundColor Cyan
Write-Host "Tools: fd, rg, bat, btop, nvim, eza, delta, Everything" -ForegroundColor Cyan
'@

# Backup existing profile if it exists
if (Test-Path $PROFILE) {
    $backupPath = "$PROFILE.backup.$(Get-Date -Format 'yyyyMMdd_HHmmss')"
    Write-Host "  Backing up existing profile to: $backupPath" -ForegroundColor Yellow
    Copy-Item $PROFILE $backupPath
}

# Create profile directory if it doesn't exist
$profileDir = Split-Path $PROFILE
if (-not (Test-Path $profileDir)) {
    New-Item -Path $profileDir -ItemType Directory -Force | Out-Null
}

# Write profile content
Set-Content -Path $PROFILE -Value $profileContent -Force

Write-Host ""
Write-Host "=== Setup Complete! ===" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "1. Close and reopen your terminal" -ForegroundColor White
Write-Host "2. Start using your new tools!" -ForegroundColor White
Write-Host ""
Write-Host "Quick reference:" -ForegroundColor Cyan
Write-Host "  Navigation:" -ForegroundColor Yellow
Write-Host "    z [path]    - Jump to frequently used directory" -ForegroundColor White
Write-Host "    zi          - Interactive directory jump" -ForegroundColor White
Write-Host "    Ctrl+T      - Fuzzy find files" -ForegroundColor White
Write-Host "    Ctrl+R      - Fuzzy search command history" -ForegroundColor White
Write-Host ""
Write-Host "  File Operations:" -ForegroundColor Yellow
Write-Host "    ls / l      - Pretty directory listing (eza)" -ForegroundColor White
Write-Host "    la          - List all files including hidden" -ForegroundColor White
Write-Host "    lt          - Tree view 2 levels" -ForegroundColor White
Write-Host "    fd <name>   - Fast file search" -ForegroundColor White
Write-Host "    bat <file>  - View file with syntax highlighting" -ForegroundColor White
Write-Host ""
Write-Host "  Search:" -ForegroundColor Yellow
Write-Host "    rg [text]   - Search text in files (ripgrep)" -ForegroundColor White
Write-Host "    Everything  - Launch Everything for PC-wide search" -ForegroundColor White
Write-Host ""
Write-Host "  Git:" -ForegroundColor Yellow
Write-Host "    git diff    - Now uses delta with syntax highlighting" -ForegroundColor White
Write-Host "    git log     - Enhanced with delta" -ForegroundColor White
Write-Host ""
Write-Host "  Other:" -ForegroundColor Yellow
Write-Host "    nvim [file] - Launch Neovim editor" -ForegroundColor White
Write-Host "    nvim .      - Open Neovim in current directory" -ForegroundColor White
Write-Host "    btop        - System resource monitor" -ForegroundColor White
Write-Host ""
Write-Host "Tool Examples:" -ForegroundColor Cyan
Write-Host "  Zoxide (smart cd):" -ForegroundColor Yellow
Write-Host "    z documents           - Jump to most used 'documents' folder" -ForegroundColor White
Write-Host "    z proj                - Jump to project folder (partial match)" -ForegroundColor White
Write-Host "    zi                    - Interactive fuzzy search through visited dirs" -ForegroundColor White
Write-Host ""
Write-Host "  Eza (better ls):" -ForegroundColor Yellow
Write-Host "    l                     - List with details and icons" -ForegroundColor White
Write-Host "    la                    - List all including hidden files" -ForegroundColor White
Write-Host "    lt                    - Tree view 2 levels deep" -ForegroundColor White
Write-Host "    eza --tree --level=3  - Deeper tree view" -ForegroundColor White
Write-Host "    eza -l --git          - Show git status for files" -ForegroundColor White
Write-Host ""
Write-Host "  Delta (git diffs):" -ForegroundColor Yellow
Write-Host "    git diff              - Syntax-highlighted diff auto-enabled" -ForegroundColor White
Write-Host "    git log -p            - Log with beautiful diffs" -ForegroundColor White
Write-Host "    git show [commit]     - View commit with delta styling" -ForegroundColor White
Write-Host ""
Write-Host "  Neovim:" -ForegroundColor Yellow
Write-Host "    nvim config.json      - Edit file" -ForegroundColor White
Write-Host "    nvim +PlugInstall     - Install plugins if configured" -ForegroundColor White
Write-Host "    Type :q to quit, :wq to save and quit" -ForegroundColor White
Write-Host ""
Write-Host "  Btop:" -ForegroundColor Yellow
Write-Host "    btop                  - Launch system monitor" -ForegroundColor White
Write-Host "    Press 'q' to quit" -ForegroundColor White
Write-Host ""
Write-Host "  Everything:" -ForegroundColor Yellow
Write-Host "    Just launch it from Start Menu or type 'Everything'" -ForegroundColor White
Write-Host "    Search entire PC instantly" -ForegroundColor White
Write-Host ""
Write-Host $PROFILE -ForegroundColor Gray
