#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_split_3x6_3(KC_ESC, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_ENT, KC_TAB, LGUI_T(KC_A), LALT_T(KC_S), LCTL_T(KC_D), LSFT_T(KC_F), KC_G, KC_H, RSFT_T(KC_J), RCTL_T(KC_K), RALT_T(KC_L), RGUI_T(KC_SCLN), KC_QUOT, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, KC_LALT, MO(2), KC_BSPC, KC_SPC, MO(1), KC_RCTL),
    [1] = LAYOUT_split_3x6_3(KC_NO, KC_GRV, KC_LPRN, KC_LCBR, KC_LBRC, KC_LT, KC_GT, KC_RBRC, KC_RCBR, KC_RPRN, KC_TILD, KC_NO, KC_NO, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_EQL, KC_PPLS, KC_NO, KC_NO, KC_QUES, KC_PIPE, KC_PMNS, KC_UNDS, KC_NO, KC_NO, KC_NO, KC_NO, KC_BSLS, KC_SLSH, KC_NO, KC_NO, MO(3), KC_NO, KC_NO, KC_NO, KC_NO),
    [2] = LAYOUT_split_3x6_3(LGUI(KC_L), KC_NO, LSG(KC_S), KC_NO, KC_NO, LCTL(KC_F4), KC_PGUP, KC_HOME, KC_TAB, KC_END, KC_NO, KC_PSCR, KC_CAPS, OS_LGUI, OS_LALT, OS_LCTL, OS_LSFT, KC_NO, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RCTL(KC_C), RCTL(KC_V), KC_NO, KC_PGDN, KC_NO, KC_NO, KC_NO, KC_NO, KC_DEL, KC_NO, KC_NO, KC_NO, KC_NO, MO(3), KC_NO),
    [3] = LAYOUT_split_3x6_3(UG_TOGG, KC_F10, KC_F9, KC_F8, KC_F7, KC_NO, KC_NO, KC_7, KC_8, KC_9, KC_NO, KC_NO, UG_HUEU, KC_F11, KC_F6, KC_F5, KC_F4, UG_VALU, KC_RCTL, KC_4, KC_5, KC_6, KC_0, KC_NO, UG_HUED, KC_F12, KC_F3, KC_F2, KC_F1, UG_VALD, KC_NO, KC_1, KC_2, KC_3, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO)
};




#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C

uint16_t get_tapping_term(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        // left home row
        case LGUI_T(KC_A):
        case LALT_T(KC_S):
        case LCTL_T(KC_D):
        case LSFT_T(KC_F):
        // right home row
        case RSFT_T(KC_J):
        case RCTL_T(KC_K):
        case RALT_T(KC_L):
        case RGUI_T(KC_SCLN):
            return 170;   // slightly tighter for home row
        default:
            return TAPPING_TERM;
    }
}

const char chordal_hold_layout[MATRIX_ROWS][MATRIX_COLS] PROGMEM =
    LAYOUT_split_3x6_3(
        'L','L','L','L','L','L',  'R','R','R','R','R','R',
        'L','L','L','L','L','L',  'R','R','R','R','R','R',
        'L','L','L','L','L','L',  'R','R','R','R','R','R',
                     'L','L','L',  'R','R','R'
    );

