---
- name: Set up my development environment
  hosts: all
  become: false # Avoid running as root
  gather_facts: false # Disable gathering facts since it require python which is not installed yet

  vars:
    home_dir: "/home/{{ ansible_user }}"
    oh_my_zsh_dir: "{{ home_dir }}/.oh-my-zsh"

  tasks:
    - include_tasks: tasks/setup_python.yml
    - include_tasks: tasks/configure_git.yml
    - include_tasks: tasks/clone_dotfiles.yml
    - include_tasks: tasks/install_nodejs.yml
    - include_tasks: tasks/install_zsh.yml
    - include_tasks: tasks/install_zsh_plugins.yml
    - include_tasks: tasks/install_tmux.yml
    - include_tasks: tasks/install_nvim.yml
